import type { Metadata } from "next";
import { OrderProvider } from "@/lib/cartContext";
import "./globals.css";
import Nav from "@/components/ui/Nav";

export const metadata: Metadata = {
  title: "ButterFlour",
  description: "Generated by create next app",
  icons: {
    icon: '/images/logo3.png',
    shortcut: '/images/logo3.png',
    apple: '/images/logo3.png'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/kve0vdb.css" />
      </head>
      <body className={'font-quicksand bg-_white'}>
        <OrderProvider>
          <Nav>
            {children}
          </Nav>
        </OrderProvider>
      </body>
    </html>
  );
}
