import type { Metadata } from "next";
import { OrderProvider } from "@/lib/cartContext";
import "./globals.css";
import Nav from "@/components/ui/Nav";

export const metadata: Metadata = {
  title: "ButterFlour",
  description: "Generated by create next app",
  icons: {
    icon: '/images/dev/logo3.png',
    shortcut: '/images/dev/logo3.png',
    apple: '/images/dev/logo3.png'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Meow+Script&family=Quicksand:wght@300..700&display=swap" rel="stylesheet" />
      </head>
      <body className={'font-qs bg-_white'}>
        <OrderProvider>
          <Nav />
          <main >
            {children}
          </main>
        </OrderProvider>
      </body> 
    </html>
  );
}
